 ---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo2
  labels:
    environment: developer
    team: infra-ops
    project: qt-ecommerce
  anno  
spec:
  containers:
    - name: mysql-container
      image: mysql
      ports:
        - containerPort: 80
          protocol: TCP 