---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels: jenkins
spec:
  replicas: 3
  minReadySeconds: 20
  selector:
    matchLabels:
      app: jenkins
      environment: production
  strategy:
    type: Rollingupdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: jenkins
        environment: production
        version: "260"
    spec:
      containers:
        - name: jenkins-container
          image: jenkins-2.60.3
          ports:
            - containerPort: 8080
              protocol: TCP
                  